<?php

class CT_CtIcon_Widget extends Case_Theme_Core_Widget_Base{
    protected $name = 'ct_icon';
    protected $title = 'Case Icons';
    protected $icon = 'eicon-alert';
    protected $categories = array( 'case-theme-core' );
    protected $params = '{"sections":[{"name":"section_icon","label":"Icons","tab":"content","controls":[{"name":"icons","label":"Icons","type":"repeater","controls":[{"name":"ct_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"}},{"name":"icon_link","label":"Icon Link","type":"url","label_block":true}]},{"name":"style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2"},"default":"style1"},{"name":"align","label":"Alignment","type":"choose","control_type":"responsive","options":{"left":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"Right","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .ct-icon1":"text-align: {{VALUE}};"}},{"name":"icon_color","label":"Icon Color","type":"color","default":"","selectors":{"{{WRAPPER}} .ct-icon1 a":"color: {{VALUE}};"}},{"name":"icon_color_hover","label":"Icon Color Hover","type":"color","default":"","selectors":{"{{WRAPPER}} .ct-icon1 a:hover":"color: {{VALUE}};"}},{"name":"bg_icon_color","label":"Icon Background Color","type":"color","default":"","selectors":{"{{WRAPPER}} .ct-icon1 a":"background-color: {{VALUE}};"},"condition":{"style":"style2"}},{"name":"bg_icon_color_hover","label":"Icon Background Color Hover","type":"color","default":"","selectors":{"{{WRAPPER}} .ct-icon1 a:hover":"background-color: {{VALUE}};"},"condition":{"style":"style2"}},{"name":"icon_border_radius","label":"Border Radius","type":"dimensions","size_units":["px"],"selectors":{"{{WRAPPER}} .ct-icon1.style2 a":"border-radius: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"condition":{"style":["style2"]}},{"name":"box_icon_width","label":"Box Icon Width","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1 a":"width: {{SIZE}}{{UNIT}};"},"condition":{"style":["style2"]}},{"name":"box_icon_height","label":"Box Icon Height","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1 a":"height: {{SIZE}}{{UNIT}};line-height: {{SIZE}}{{UNIT}};"},"condition":{"style":["style2"]}},{"name":"icon_typography","label":"Icon Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .ct-icon1 a"},{"name":"icon_space","label":"Icon Spacer","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":300}},"selectors":{"{{WRAPPER}} .ct-icon1 a":"margin-right: {{SIZE}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}